# Generated by Django 4.2.3 on 2023-07-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tmpcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('body', models.TextField()),
                ('sys_show', models.IntegerField(default=1, verbose_name='删除字段')),
                ('sys_add', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
