# Generated by Django 4.2.3 on 2023-07-23 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', '学习工具'), ('1', '思考工具'), ('2', '分类工具'), ('3', '分步工具')], default='0', max_length=20, verbose_name='类型')),
                ('casetitle', models.CharField(max_length=64, verbose_name='框架标题')),
                ('caseprofile', models.CharField(blank=True, max_length=200, null=True, verbose_name='简介')),
                ('creater', models.CharField(max_length=64, verbose_name='创建人')),
                ('sys_show', models.IntegerField(default=1, verbose_name='删除字段')),
                ('sys_add', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(default='0', verbose_name='Case_content_id')),
                ('uniqueid', models.CharField(max_length=60, verbose_name='方案唯一标识')),
                ('solution', models.CharField(max_length=200, verbose_name='方案')),
                ('is_title', models.IntegerField(default='1', verbose_name='1,标题；0，内容')),
                ('creater', models.CharField(max_length=64, verbose_name='创建人')),
                ('sys_show', models.IntegerField(default=1, verbose_name='删除字段')),
                ('sys_add', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Case_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casecontent', models.CharField(max_length=200, verbose_name='框架内容')),
                ('sub_title', models.IntegerField(default='0', verbose_name='0，有输入；1，子标题没有输入')),
                ('creater', models.CharField(max_length=64, verbose_name='创建人')),
                ('sys_show', models.IntegerField(default=1, verbose_name='删除字段')),
                ('sys_add', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('casetitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casepoint.case_title', verbose_name='标题')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
