# Generated by Django 4.2.3 on 2023-07-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casepoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_title',
            name='category',
            field=models.CharField(choices=[('学习工具', '学习工具'), ('思考工具', '思考工具'), ('分类工具', '分类工具'), ('分步工具', '分步工具')], default='0', max_length=20, verbose_name='类型'),
        ),
    ]
