# Generated by Django 3.0 on 2019-12-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_flage', models.IntegerField(default='0', verbose_name='顺序')),
                ('name', models.CharField(max_length=64, verbose_name='框架')),
                ('creater', models.CharField(max_length=64, verbose_name='创建人')),
                ('is_show', models.IntegerField(default=1, verbose_name='删除字段')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type_id', models.IntegerField(default='0', verbose_name='父级type')),
                ('name', models.CharField(max_length=64, verbose_name='框架分类')),
                ('is_show', models.IntegerField(default=1, verbose_name='删除字段')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_flage', models.IntegerField(default='0', verbose_name='属于第几个方案')),
                ('name', models.CharField(max_length=64, verbose_name='框架')),
                ('creater', models.CharField(max_length=64, verbose_name='创建人')),
                ('is_show', models.IntegerField(default=1, verbose_name='删除字段')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('frame_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testuu.Frame', verbose_name='类型')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testuu.TypeDetail', verbose_name='类型'),
        ),
    ]
