# Generated by Django 3.0 on 2019-12-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testuu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedetail',
            name='level',
            field=models.IntegerField(default=0, verbose_name='级别'),
        ),
    ]
