# Generated by Django 3.0 on 2019-12-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testuu', '0002_typedetail_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedetail',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='frame',
            name='order_flage',
        ),
        migrations.AddField(
            model_name='frame',
            name='title_content',
            field=models.IntegerField(default='0', verbose_name='标题内容标识0：标题，1：内容'),
        ),
    ]
