# Generated by Django 3.0 on 2019-12-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testuu', '0003_auto_20191222_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='type_id',
            new_name='type',
        ),
    ]
