# Generated by Django 3.0 on 2019-12-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testuu', '0004_auto_20191222_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame_union',
            field=models.IntegerField(default='0', verbose_name='frame唯一号'),
        ),
    ]
