# Generated by Django 3.0 on 2019-12-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testuu', '0005_frame_frame_union'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='frame_id',
            new_name='frame',
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_union',
            field=models.IntegerField(default='0', verbose_name='solution唯一号'),
        ),
    ]
