# Generated by Django 4.2.3 on 2023-07-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('日程安排', '日程安排'), ('项目记录', '项目记录'), ('备忘mark', '备忘mark')], default='0', max_length=20)),
                ('content', models.TextField(verbose_name='日程安排')),
                ('user', models.CharField(default='', max_length=12, verbose_name='执行人员')),
                ('start_time', models.DateTimeField(default='', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default='', verbose_name='结束时间')),
                ('sys_add', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('sys_show', models.IntegerField(default=1, verbose_name='删除字段')),
            ],
            options={
                'verbose_name': '日程安排',
                'verbose_name_plural': '日程安排',
            },
        ),
        migrations.CreateModel(
            name='FeedbackSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, choices=[('计划进度', '计划进度'), ('日程安排', '日程安排')], default='中', max_length=8, null=True, verbose_name='优先级')),
                ('part_id', models.IntegerField(default='', verbose_name='计划表ID')),
                ('content', models.TextField(verbose_name='反馈')),
                ('sys_add', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('sys_show', models.IntegerField(default=1, verbose_name='删除字段')),
            ],
            options={
                'verbose_name': '反馈总结',
                'verbose_name_plural': '反馈总结',
            },
        ),
        migrations.CreateModel(
            name='PlanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default='', max_length=255, verbose_name='任务名称')),
                ('p_start_time', models.DateField(blank=True, default='', null=True, verbose_name='计划开始时间')),
                ('p_finish_time', models.DateField(blank=True, default='', null=True, verbose_name='计划结束时间')),
                ('a_start_time', models.DateField(blank=True, default='', null=True, verbose_name='实际开始时间')),
                ('a_finish_time', models.DateField(blank=True, default='', null=True, verbose_name='实际结束时间')),
                ('progress', models.CharField(default='', max_length=4, verbose_name='完成进度')),
                ('priority', models.CharField(blank=True, choices=[('高', '高'), ('中', '中'), ('低', '低'), ('回归', '回归')], default='中', max_length=6, null=True, verbose_name='优先级')),
                ('executor', models.CharField(default='未分配', max_length=12, verbose_name='执行人员')),
                ('plan_prev', models.IntegerField(default=1, verbose_name='任务上级')),
                ('plan_next', models.IntegerField(default=1, verbose_name='任务上级')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('sys_show', models.IntegerField(default=1, verbose_name='删除字段')),
            ],
            options={
                'verbose_name': '计划进度',
                'db_table': 'test_progress_schedule',
                'ordering': ['p_start_time'],
                'unique_together': {('task_id', 'plan_prev', 'plan_next')},
            },
        ),
    ]
