# Generated by Django 4.2.3 on 2023-07-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='groupname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
