# Generated by Django 4.2.3 on 2023-07-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_dailyschedule_groupname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyschedule',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='dailyschedule',
            old_name='groupname',
            new_name='groupId',
        ),
        migrations.RenameField(
            model_name='dailyschedule',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='dailyschedule',
            old_name='content',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='category',
            field=models.CharField(choices=[('日程安排', '日程安排'), ('项目记录', '项目记录'), ('备忘mark', '备忘mark')], default='日程安排', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='sys_add',
            field=models.DateField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
